#!/usr/bin/env bash
# Script that displays information about subdomains
# Usage: ./0-world_wide_web domain [subdomain]

# Function to display subdomain info
check_subdomain() {
    local domain=$1
    local subdomain=$2

    # shellcheck disable=SC2086
    info=$(dig $subdomain.$domain | awk '/ANSWER SECTION:/{found=1; next} found && NF{print $4, $5; exit}')

    record_type=$(echo $info | awk '{print $1}')
    destination=$(echo $info | awk '{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        check_subdomain "$domain" "$sub"
    done
else
    check_subdomain "$domain" "$subdomain"
fi
